name: Gitleaks Secrets Scan
on: [push]
jobs:
  Credentials_Scanning:
    runs-on: ubuntu-latest
    steps:
 #     - name: Checkout code
 #       uses: actions/checkout@v3
  #      with:
  #        fetch-depth: 0
      - name: Run Gitleaks from container
        run: |
            git clone https://github.com/christosservosNCIN/WebGoat.git
            docker run --user root --volume ${{ github.workspace }}:/src --interactive zricethezav/gitleaks detect --source=/src --verbose --report-path /src/gitleaks-reports.json
        continue-on-error: true
        
      #- name: upload_artifacts   
       # uses: actions/upload-artifact@v3
        #with:
         # name: Gitleaks_Artifact
          #path:  ${{ github.workspace }}/gitleaks-reports.json
          
      - name: Depcheck
        uses: dependency-check/Dependency-Check_Action@main
        id: Depcheck
        with:
          project: 'test'
          path: '.'
          format: 'HTML'
          out: 'reports' # this is the default, no need to specify unless you wish to override it
          args: >
            --enableRetired
      - name: Upload Test results for DCheck and Gitleaks
        uses: actions/upload-artifact@master
        with:
           name: Dependency_check artifact + gitleaks artifact
           path: |
                ${{github.workspace}}/dependency-check-report.html
                ${{ github.workspace }}/gitleaks-reports.json
